apiVersion: v1
kind: Service
metadata:
  name: crapi-web
  labels:
    app: crapi-web
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: ClusterIP
  selector:
    app: crapi-web
