kind: PersistentVolumeClaim
apiVersion: v1
 
metadata:
  name: mongodb-pv-claim
  labels:
    app: mongo
 
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
