kind: PersistentVolumeClaim
apiVersion: v1
 
metadata:
  name: postgres-pv-claim
  labels:
    app: postgresdb
 
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
