name: Generate crAPI load

on:
  # pull_request:
  #   paths:
  #     - .github/workflows/generate_load.yml
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  generate-crapi-load:
    name: Generate crAPI load
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Load against prod Demo
        uses: apardo04/locust-github-action@master
        with:
          LOCUSTFILE: "crAPI/services/loadgen/locustfile.py"
          URL:  "http://crapi-prod.levo.ai"
          USERS: "5"
          RATE: "5"
          RUNTIME: "3m"

      - name: Run Load against Dev e2e
        uses: apardo04/locust-github-action@master
        with:
          LOCUSTFILE: "crAPI/services/loadgen/locustfile.py"
          URL:  "http://34.170.155.55"
          USERS: "5"
          RATE: "5"
          RUNTIME: "3m"
