name: Build Demo App

on:
  pull_request:
    paths:
      - '.github/workflows/*-demo-apps.yml'
      - 'MalSchema/**'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-demo-app-image:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: MalSchema Dockerhub push
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/malschema
          path: ./MalSchema
          tag: latest
          cache: true
          extra_args: "--cache-repo levoai/levo-malschema-cache"
